import Link from "next/link";
import styled from "styled-components";
import Dropdown from "../Dropdown";
import Head from "next/head";

import { useRef } from "react";

import ChevronDown from "../../icons/ChevronDown";

const Header = styled.header`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 1rem;
  background-color: ${({ theme }) => theme.colors.white};
  color: ${({ theme }) => theme.colors.brand};
`;

const Navbar = styled.nav`
  display: flex;
  gap: 1rem;
`;

const NavLink = styled.a`
  font-weight: bold;
  color: ${({ theme }) => theme.colors.brand};
  text-decoration: none;

  &:hover {
    text-decoration: underline;
  }
`;

interface LayoutProps {
  children: React.ReactNode;
  session: any;
}

const Layout: React.FC<LayoutProps> = ({ children, session }) => {
  const accountDropdownRef = useRef<any>({});

  console.log(session);
  return (
    <>
      <Head>
        <title>Verby </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        {/* <Link href="/">
          <a>My App</a>
        </Link> */}

        <Dropdown
          id="voiceDropdown"
          selectedItemText={"dfd"}
          ref={accountDropdownRef}
          icon={<ChevronDown />}
        >
          <ul>
            <li>Logout</li>
          </ul>
        </Dropdown>
        <Navbar>
          <Link href="/about">
            <NavLink>About</NavLink>
          </Link>
          <Link href="/contact">
            <NavLink>Contact</NavLink>
          </Link>
        </Navbar>
      </Header>
      <main className="flex min-h-screen bg-gradient-to-b from-[#f1f1f1] to-[#e9e9e9]">
        {children}
      </main>
    </>
  );
};

export default Layout;
