import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";
import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import React, { useState, useEffect } from "react";
import { useSession } from "@supabase/auth-helpers-react";
import { Check } from "lucide-react";
import { api } from "@/utils/api";
import { useTheme } from "styled-components";
import styled from "styled-components";

const PricingStyle = styled.section`
  .subscribe-btn {
    position: relative;
    overflow: hidden;
    background-image: linear-gradient(to right, #0b89ee, #1371e9);
    transition: all 0.2s ease-in-out;
    display: inline-block;
    padding: 12px 20px;
    text-decoration: none;
    border-radius: 4px;
  }

  .subscribe-btn span {
    position: relative;
    color: white;
  }

  .subscribe-btn::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: linear-gradient(to right, #1895f4, #1e79e8);
    opacity: 0;
    transition: opacity 0.2s ease-in-out;
  }

  .subscribe-btn:hover::before {
    opacity: 1;
  }
`;

const Upgrade: NextPage = () => {
  const supabase = useSupabaseClient();

  const theme = useTheme();
  const router = useRouter();
  const session = useSession();
  const [loading, setLoading] = useState<boolean>(true);
  const queryResult = api.checkout.fetchProducts.useQuery();
  const { data } = queryResult;

  console.log(data);

  return (
    <>
      <Head>
        <title>Vontane | Upgrade </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" block overflow-auto  bg-gradient-to-b from-[#f1f1f1] to-[#e9e9e9]">
        <Header />
        {/* <div className="item-center flex h-screen items-center justify-center">
          <div className="h-[420px] w-80 transform rounded-3xl border-4 border-[#0E78EF] bg-white p-8 text-center text-gray-500 shadow-xl">
            <h1 className="text-2xl font-semibold text-[#0E78EF]">Premium</h1>
            <p className="pt-2 tracking-wide">
              <span className="align-top text-black">£ </span>
              <span className="text-3xl text-black">49</span>
              <span className="font-medium text-gray-500">/ month</span>
            </p>
            <hr className="border-1 mt-4 border-gray-600" />
            <div className="pt-8">
              <p className="flex text-left font-semibold text-gray-500">
                <Check />
                <span className="pl-2">
                  <span className="text-[#0E78EF]">Unlimited</span> Docs and
                  Slide Exports
                </span>
              </p>
              <p className="flex text-left font-semibold text-gray-500">
                <Check />
                <span className="pl-2">
                  <span className="text-[#0E78EF]">Unlimited</span> Usage of AI
                </span>
              </p>
              <p className="flex pt-5 text-left font-semibold text-gray-500">
                <Check />
                <span className="pl-2">
                  <span className="text-[#0E78EF]">Unlimited</span> Workspaces
                </span>
              </p>
             

              <a href="#" className="">
                <p className="mt-8 w-full rounded-xl bg-blue-600 py-4 text-white">
                  <span className="font-medium">Choose Plan</span>
                  <span className="material-icons pl-2 align-middle text-sm">
                    east
                  </span>
                </p>
              </a>
            </div>
          </div>
        </div>
         */}

        <PricingStyle className="relative z-20 overflow-hidden bg-white pt-20 pb-12 lg:pt-[120px] lg:pb-[90px]">
          <div className="container mx-auto">
            <div className="-mx-4 flex flex-wrap">
              <div className="w-full px-4">
                <div className="mx-auto mb-[60px] max-w-[510px] text-center lg:mb-20">
                  <h2 className="text-dark mb-4 text-3xl font-bold sm:text-4xl md:text-[40px]">
                    Upgrade
                  </h2>
                </div>
              </div>
            </div>
            <div className="-mx-4 flex flex-wrap justify-center">
              <div className="w-full px-4 md:w-1/2 lg:w-1/3">
                <div className="relative z-10 mb-10 overflow-hidden rounded-xl border border-gray-200 bg-white py-10 px-8 shadow-md sm:p-12 lg:py-10 lg:px-6 xl:p-12">
                  <span className="mb-4 block text-lg font-semibold text-[#0E78EF]">
                    Pro Plan
                  </span>
                  <h2 className="text-dark mb-5 text-[42px] font-bold">
                    £49
                    <span className="text-body-color text-base font-medium">
                      {" "}
                      / month{" "}
                    </span>
                  </h2>
                  <p className="text-body-color mb-8 border-b border-[#F2F2F2] pb-8 text-base">
                    Perfect for using in a Business website or a client project.
                  </p>
                  <div className="mb-7">
                    {/* <p className="text-body-color mb-1 text-base leading-loose">
                      5 Users
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      All UI components
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Lifetime access
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Free updates
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Use on 3 (Three) project
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      4 Months support
                    </p> */}

                    <p className="flex text-left text-base font-semibold leading-loose text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span> Docs
                        and Slide Exports
                      </span>
                    </p>
                    <p className="flex text-left font-semibold text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span> Usage
                        of AI
                      </span>
                    </p>
                    <p className="flex pt-5 text-left font-semibold text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span>{" "}
                        Workspaces
                      </span>
                    </p>
                  </div>
                  <a
                    href="javascript:void(0)"
                    className="subscribe-btn block w-full rounded-md border p-4 text-center text-base font-semibold text-white transition hover:bg-opacity-10"
                  >
                    <span>Subscribe</span>
                  </a>
                  <div>
                    <span className="absolute right-0 top-7 z-[-1]">
                      <svg
                        width="77"
                        height="172"
                        viewBox="0 0 77 172"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <circle
                          cx="86"
                          cy="86"
                          r="86"
                          fill="url(#paint0_linear)"
                        />
                        <defs>
                          <linearGradient
                            id="paint0_linear"
                            x1="86"
                            y1="0"
                            x2="86"
                            y2="172"
                            gradientUnits="userSpaceOnUse"
                          >
                            <stop stopColor="#1177EF" stopOpacity="0.22 " />
                            <stop
                              offset="1"
                              stopColor="#01AEF4"
                              stopOpacity="0"
                            />
                          </linearGradient>
                        </defs>
                      </svg>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </PricingStyle>
      </main>
    </>
  );
};

export default Upgrade;
