import { useSupabaseClient } from "@supabase/auth-helpers-react";
import { useRouter } from "next/router";
import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "@/components/Header";
import React, { useState, useEffect } from "react";
import { useSession } from "@supabase/auth-helpers-react";
import { Check } from "lucide-react";
import { api } from "@/utils/api";
import { useTheme } from "styled-components";
import styled from "styled-components";
import { motion, AnimatePresence } from "framer-motion";
import { getStripe } from "@/utils/stripe-client";
import LoadingSpinner from "@/icons/LoadingSpinner";

const PricingStyle = styled.section`
  .subscribe-btn {
    position: relative;
    overflow: hidden;
    background-image: linear-gradient(to right, #0b89ee, #1371e9);
    transition: all 0.2s ease-in-out;
    display: inline-block;
    padding: 12px 20px;
    text-decoration: none;
    border-radius: 4px;
  }

  .subscribe-btn span {
    position: relative;
    color: white;
  }

  .subscribe-btn::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-image: linear-gradient(to right, #1895f4, #1e79e8);
    opacity: 0;
    transition: opacity 0.2s ease-in-out;
  }

  .subscribe-btn:hover::before {
    opacity: 1;
  }
`;

const Upgrade: NextPage = () => {
  const supabase = useSupabaseClient();

  const theme = useTheme();
  const router = useRouter();
  const session = useSession();
  const [loading, setLoading] = useState<boolean>(false);

  const [toggle, setToggle] = useState(true);
  const toggleClass = " transform translate-x-[22px]";
  const queryResult = api.checkout.fetchProducts.useQuery();
  const { data } = queryResult;

  const prices = data && data[0].prices;

  console.log(prices);
  const [selectedPrice, setSelectedPrice] = useState("");

  useEffect(() => {
    if (prices) {
      if (toggle) {
        setSelectedPrice(prices[1].id);
      } else {
        setSelectedPrice(prices[0].id);
      }
    }
  }, [toggle]);

  useEffect(() => {
    if (prices) {
      setSelectedPrice(prices[1].id);
      console.log(prices[1]);
    }
  }, [prices]);

  const createCheckoutSessionMutation =
    api.checkout.createCheckoutSession.useMutation();

  const createCheckoutSession = async (_price: string) => {
    if (loading) return;
    try {
      setLoading(true);
      const { sessionId } = await createCheckoutSessionMutation.mutateAsync({
        price: _price,
      });

      console.log(sessionId);

      const stripe = await getStripe();
      setLoading(false);
      stripe?.redirectToCheckout({ sessionId });
    } catch (error) {
      setLoading(false);
      console.error("Error creating checkout session:", error);
    }
  };

  useEffect(() => {
    if (!session) {
      router.push(`/login?next=${encodeURIComponent(router.asPath)}`);
    }
  }, [session, router]);

  const priceVariants = {
    hidden: { opacity: 0, scale: 0.6 },
    visible: { opacity: 1, scale: 1 },
    exit: { opacity: 0, scale: 0.6 },
  };

  return (
    <>
      <Head>
        <title>Vontane | Upgrade </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" block overflow-auto  bg-gradient-to-b from-[#f1f1f1] to-[#e9e9e9]">
        <Header />
        <PricingStyle className="relative z-20 overflow-hidden bg-white pt-20 pb-12 lg:pt-[120px] lg:pb-[90px]">
          <div className="container mx-auto">
            <div className="-mx-4 flex flex-wrap">
              <div className="w-full px-4">
                <div className="mx-auto mb-[20px] max-w-[510px] text-center lg:mb-10">
                  <h2 className="text-dark mb-4 text-3xl font-bold sm:text-4xl md:text-[40px]">
                    Upgrade
                  </h2>
                </div>
              </div>
            </div>

            <div className="relative mt-5 mb-5 flex items-center justify-center gap-5">
              {/*   Switch Container */}
              <span className="flex text-lg font-semibold text-black">
                Monthly
              </span>
              <div
                className="relative flex h-[24px] w-[48px] cursor-pointer items-center  rounded-full border border-[#0E78EF] bg-white p-1"
                onClick={() => {
                  setToggle(!toggle);
                }}
              >
                {/* Switch */}
                <div
                  className={
                    "absolute left-[2px] h-[20px] w-[20px] transform rounded-full bg-[#0E78EF] shadow-md duration-300 ease-in-out" +
                    (toggle ? null : toggleClass)
                  }
                ></div>
              </div>
              <span className="relative flex text-lg font-semibold text-black">
                Annual
                <div className="absolute left-[70px] w-[80px] rounded-md border border-[0E78EF] p-1 text-xs text-gray-500">
                  Save 38%!
                </div>
              </span>
            </div>
            <div className="-mx-4 flex flex-wrap justify-center">
              <div className="w-full px-4 md:w-1/2 lg:w-[420px]">
                <div className="relative z-10 mb-10 overflow-hidden rounded-xl border border-gray-200 bg-white py-10 px-8 shadow-md sm:p-12 lg:py-10 lg:px-6 xl:p-12">
                  <span className="mb-4 block text-[28px] text-lg font-semibold text-[#0E78EF]">
                    Pro Plan{" "}
                    <span className="text-sm text-gray-500">
                      {" "}
                      {toggle ? "(Billed Monthly)" : "(Billed Annually)"}
                    </span>
                  </span>

                  <h2 className=" text-dark relative mb-5 text-[42px] font-bold">
                    <div className="relative h-[70px]">
                      <AnimatePresence>
                        {toggle ? (
                          <motion.span
                            className="absolute top-0 left-0 block"
                            initial="hidden"
                            animate="visible"
                            exit="exit"
                            variants={priceVariants}
                            transition={{ duration: 0.4 }}
                            key="monthly"
                          >
                            £39
                          </motion.span>
                        ) : (
                          <motion.span
                            className="absolute top-0 left-0 block"
                            initial="hidden"
                            animate="visible"
                            exit="exit"
                            variants={priceVariants}
                            transition={{ duration: 0.4 }}
                            key="annual"
                          >
                            £24
                          </motion.span>
                        )}
                      </AnimatePresence>
                      <span className="text-body-color absolute top-[25px] left-[100px] text-base font-medium">
                        {" "}
                        per month{" "}
                      </span>
                    </div>
                  </h2>
                  <p className="text-body-color mb-4 border-b border-[#F2F2F2] pb-4 text-base">
                    For Commercial use.
                  </p>
                  <div className="mb-7">
                    {/* <p className="text-body-color mb-1 text-base leading-loose">
                      5 Users
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      All UI components
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Lifetime access
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Free updates
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      Use on 3 (Three) project
                    </p>
                    <p className="text-body-color mb-1 text-base leading-loose">
                      4 Months support
                    </p> */}

                    <p className="mt-3  flex items-center text-left text-base font-semibold leading-loose text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span> Docs
                        and Slide Exports
                      </span>
                    </p>
                    <p className="mt-2  flex items-center text-left font-semibold leading-loose text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span> Usage
                        of AI
                      </span>
                    </p>
                    <p className="mt-3 flex items-center text-left font-semibold leading-loose text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Unlimited</span>{" "}
                        Workspaces
                      </span>
                    </p>
                    <p className="mt-3  flex  items-center text-left font-semibold leading-loose text-gray-500">
                      <Check />
                      <span className="pl-2">
                        <span className="text-[#0E78EF]">Priority</span>{" "}
                        customer support
                      </span>
                    </p>
                  </div>
                  <button
                    onClick={() => createCheckoutSession(selectedPrice)}
                    className="subscribe-btn flex w-full items-center justify-center rounded-md border p-4 text-center text-base font-semibold text-white transition hover:bg-opacity-10"
                  >
                    <div className="flex items-center justify-center">
                      {loading ? (
                        <LoadingSpinner strokeColor="#ffffff" />
                      ) : (
                        <span className="ml-2">Subscribe</span>
                      )}
                    </div>
                  </button>
                  <div>
                    <span className="absolute right-0 top-7 z-[-1]">
                      <svg
                        width="77"
                        height="172"
                        viewBox="0 0 77 172"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <circle
                          cx="86"
                          cy="86"
                          r="86"
                          fill="url(#paint0_linear)"
                        />
                        <defs>
                          <linearGradient
                            id="paint0_linear"
                            x1="86"
                            y1="0"
                            x2="86"
                            y2="172"
                            gradientUnits="userSpaceOnUse"
                          >
                            <stop stopColor="#1177EF" stopOpacity="0.22 " />
                            <stop
                              offset="1"
                              stopColor="#01AEF4"
                              stopOpacity="0"
                            />
                          </linearGradient>
                        </defs>
                      </svg>
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </PricingStyle>
      </main>
    </>
  );
};

export default Upgrade;
